### ISSUE TITLE
(Android bug?) The get it/view button is not working

### ISSUE THREAD

**Issue by HotKentang** [SergeyMC9730/levelhistory#1]
So I wanna copy the level of someone who got their account hacked & the only way I can do that is to go through the GD level viewer page by tapping the get it/view button & it didn't work (it won't let me go into the level viewer page)

![Screenshot_2024-04-29-19-21-41-116_com geode launcher](https://github.com/SergeyMC9730/levelhistory/assets/161263883/c7b3c749-2a1a-4f99-b739-85ed31dd6ae7)

Pls fix if you have time because there are deleted levels who have SFX's and the only way to download those sfx is by going into the level viewer page which you can't do it rn due to the button isn't working, thanks ;)

**Comment by SergeyMC9730** [comment]
Will be fixed in `v1.0.3`

**Comment by SergeyMC9730** [comment]
Fixed in `v1.0.3`. This mod version would release soon
